# Generated by Django 4.2 on 2025-02-16 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultiesInJapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HowYouFoundUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UseUzbekCommunityHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('years_in_japan', models.IntegerField()),
                ('living_city', models.CharField(max_length=50)),
                ('does_work', models.BooleanField(default=False)),
                ('workplace', models.CharField(max_length=100)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='women_event.education')),
                ('languages', models.ManyToManyField(blank=True, to='women_event.language')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulties_in_japan_other', models.CharField(max_length=1000)),
                ('your_priority_problem', models.CharField(max_length=1000)),
                ('difficulties_in_japan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='women_event.difficultiesinjapan')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women_event.responder')),
                ('use_uzbek_community_help', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='women_event.useuzbekcommunityhelp')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_topic_other', models.CharField(max_length=100)),
                ('interactive_style', models.ManyToManyField(to='women_event.interactivestyle')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women_event.responder')),
                ('seminar_topic', models.ManyToManyField(to='women_event.seminartopics')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvements_for_future', models.TextField()),
                ('howyoufoundus_other', models.CharField(max_length=100)),
                ('howyoufoundus', models.ManyToManyField(to='women_event.howyoufoundus')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women_event.responder')),
            ],
        ),
    ]
