# Generated by Django 4.2 on 2025-02-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontwo',
            name='difficulties_in_japan',
        ),
        migrations.AddField(
            model_name='questiontwo',
            name='difficulties_in_japan',
            field=models.ManyToManyField(to='women_event.difficultiesinjapan'),
        ),
    ]
