# Generated by Django 4.2 on 2025-02-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_event', '0002_remove_questiontwo_difficulties_in_japan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='education_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
