# Generated by Django 4.2 on 2025-02-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_event', '0004_alter_questionfour_improvements_for_future_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionthree',
            name='comments',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
